AllCops:
  Exclude:
    - 'db/**/*'
  RunRailsCops: true

Style/DotPosition:
  EnforcedStyle: leading

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/routes.rb'
    - 'config/routes/*'

Style/FileName:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
